### ISSUE TITLE
The entity "nbsp" was referenced, but not declared

### ISSUE THREAD

**Issue by FabioBo** [dgm9704/Xoxo#58]
Hi, i've a xbrl file that contain this row:
....
        &lt;font size="2" face="Times New Roman"&gt;&lt;span style="font-size: 11.0pt"&gt;&nbsp;&lt;/span&gt;&lt;/font&gt;
....
when we execute Instance.FromFile(....) we have this error:The entity "nbsp" was referenced, but not declared.
Have you any suggestion fir this issue?
Thank you

**Comment by dgm9704** [comment]
Hello,
thank you for hetting in touch, and sorry to hear that there is a problem.
If the file is iXBRL then I am afraid that Diwen.Xbrl cannot handle it yet.
If it is a normal XBRL file then I would see the whole file (or at least a bigger part of it)
if possible so I can investigate.
(Of course I dont want to see anything confidential)

— 
John

**Comment by FabioBo** [comment]
Hi, thank you for your quick answer.
Our file is (i mean) a normal xbrl, the problem is in the keyword CommentoDisponibilitaUtilizzoPatrimonioNetto
How could i send you a sample xbrl file?
Thank you

**Comment by dgm9704** [comment]
If it doesn’t contain anything secret, you could upload it to filesharing site (pastebin or something) or you can send it straight to me 
John.nordberg@gmail.com

John

**Comment by dgm9704** [comment]
Silly me, I was answering from my phone and didn't realize that you can attach file here to the issue. (provided that it doesn't contain anything sensitive)

**Comment by dgm9704** [comment]
I got the file now thank you.
The problem is that Diwen.Xbrl sees the content of fact which is html and tries to process it like it was part of the xbrl. 
That is the reason for the error you see, and you would see countless others once you got past that.
Options for getting around this: 
- encode any content (not part of the xbrl) that is markup (html) with function such as HTMLEncode ?
- enclose any markup content in CDATA section ?
- check if the specifications for the specific taxonomy / reporting framework have some clues as how to handle this content (component has only been tested with EBA and EIOPA ITS and some SBR)
- modify Diwen.Xbrl to better understand that specific type of XBRL reporting ?
I need to spend a few hours on my day job, but will get back to this.

**Comment by FabioBo** [comment]
Did you received xbrl file enclosed to my previous e-mail?
Fabio

Da: John Nordberg [mailto:notifications@github.com]
Inviato: giovedì 30 novembre 2017 08:06
A: dgm9704/Xoxo <Xoxo@noreply.github.com>
Cc: Fabio Borghi <fabio.borghi@initec.it>; Author <author@noreply.github.com>
Oggetto: Re: [dgm9704/Xoxo] The entity "nbsp" was referenced, but not declared (#58)


Silly me, I was answering from my phone and didn't realize that you can attach file here to the issue. (provided that it doesn't contain anything sensitive)

**Comment by FabioBo** [comment]
Hi, currently we have "replaced" &nbsp from html portion of text because of we are only interested on a few reporting information and not this text.
Here is our "workaround":
`                //var first = Instance.FromFile(documento);
                String xmlString = System.IO.File.ReadAllText(documento);
                xmlString = xmlString.Replace("&nbsp", "");
                var first = Instance.FromXml(xmlString);
`
we have removed "&ncsp" from original document and replace Instance.FromFile with Instance.FromXml
Thank you
