### ISSUE TITLE
documentInfo.features: values cannot be other that string, which violates the spec

### ISSUE THREAD

**Issue by kenavn** [dgm9704/Xoxo#88]
## Expected

Reading a xbrl.json file that contains a field named "documentType" with a boolean value `true`;
`  "documentInfo": {
    "documentType": "https://xbrl.org/2021/xbrl-json",
    "features": {
      "xbrl:canonicalValues": true
    }`
is expected to work. Reason; it is valid [json](https://www.json.org/json-en.html). It is also expected based on [xblr-json spec pt. 5](https://www.xbrl.org/Specification/xbrl-json/REC-2021-10-13/xbrl-json-REC-2021-10-13.html).

## Actual

`var rep = Diwen.Xbrl.Json.Report.FromFile(jsonPath);`

Fails as such;

`System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.documentInfo.features.xbrl:canonicalValues | LineNumber: 4 | BytePositionInLine: 34.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'True' as a string.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.JsonConverter`

**Comment by dgm9704** [comment]
Thank you for reporting this! I'll take a look as soon as I have time, hopefully during this week.

**Comment by dgm9704** [comment]
There is now a new version 3.4.1 that has a fix for this issue. I'm sure there are still some bugs or things missing from the XBRL-JSON implementation or handling, please feel free to report anything with a low threshold. The library is mostly based on a limited subset of things I see in my dayjob, and these bug reports are super helpful with fixing things that I would miss otherwise.

**Comment by kenavn** [comment]
Thanks :)
